const serviceProviders = [
  // Room - Gas Filling
  {
    id: 1,
    name: "Service Provider 1",
    category: "Room",
    subcategory: "Gas Filling",
    rating: 4.5,
    image: require("../../assets/onboarding1.jpg"),
  },
  {
    id: 2,
    name: "Service Provider 2",
    category: "Room",
    subcategory: "Gas Filling",
    rating: 4.2,
    image: require("../../assets/onboarding1.jpg"),
  },
  {
    id: 3,
    name: "Service Provider 3",
    category: "Room",
    subcategory: "Gas Filling",
    rating: 4.8,
    image: require("../../assets/onboarding1.jpg"),
  },
  // Room - Laundry
  {
    id: 4,
    name: "Service Provider 4",
    category: "Room",
    subcategory: "Laundry",
    rating: 4.7,
    image: require("../../assets/onboarding1.jpg"),
  },
  {
    id: 5,
    name: "Service Provider 5",
    category: "Room",
    subcategory: "Laundry",
    rating: 4.3,
    image: require("../../assets/onboarding1.jpg"),
  },
  {
    id: 6,
    name: "Service Provider 6",
    category: "Room",
    subcategory: "Laundry",
    rating: 4.6,
    image: require("../../assets/onboarding1.jpg"),
  },
  // Tutoring - Courses Tutoring
  {
    id: 7,
    name: "Service Provider 7",
    category: "Tutoring",
    subcategory: "Courses Tutoring",
    rating: 4.9,
    image: require("../../assets/onboarding2.jpg"),
  },
  {
    id: 8,
    name: "Service Provider 8",
    category: "Tutoring",
    subcategory: "Courses Tutoring",
    rating: 4.4,
    image: require("../../assets/onboarding2.jpg"),
  },
  {
    id: 9,
    name: "Service Provider 9",
    category: "Tutoring",
    subcategory: "Courses Tutoring",
    rating: 4.7,
    image: require("../../assets/onboarding2.jpg"),
  },
  // Tutoring - Programming Languages
  {
    id: 10,
    name: "Service Provider 10",
    category: "Tutoring",
    subcategory: "Programming Languages",
    rating: 4.2,
    image: require("../../assets/onboarding2.jpg"),
  },
  {
    id: 11,
    name: "Service Provider 11",
    category: "Tutoring",
    subcategory: "Programming Languages",
    rating: 4.6,
    image: require("../../assets/onboarding2.jpg"),
  },
  {
    id: 12,
    name: "Service Provider 12",
    category: "Tutoring",
    subcategory: "Programming Languages",
    rating: 4.8,
    image: require("../../assets/onboarding2.jpg"),
  },
  // Design - UI/UX Designs
  {
    id: 13,
    name: "Service Provider 13",
    category: "Design",
    subcategory: "UI/UX Designs",
    rating: 4.3,
    image: require("../../assets/onboarding3.jpg"),
  },
  {
    id: 14,
    name: "Service Provider 14",
    category: "Design",
    subcategory: "UI/UX Designs",
    rating: 4.7,
    image: require("../../assets/onboarding3.jpg"),
  },
  {
    id: 15,
    name: "Service Provider 15",
    category: "Design",
    subcategory: "UI/UX Designs",
    rating: 4.9,
    image: require("../../assets/onboarding3.jpg"),
  },
  // Design - Graphic Designs
  {
    id: 16,
    name: "Service Provider 16",
    category: "Design",
    subcategory: "Graphic Designs",
    rating: 4.6,
    image: require("../../assets/onboarding3.jpg"),
  },
  {
    id: 17,
    name: "Service Provider 17",
    category: "Design",
    subcategory: "Graphic Designs",
    rating: 4.5,
    image: require("../../assets/onboarding3.jpg"),
  },
  {
    id: 18,
    name: "Service Provider 18",
    category: "Design",
    subcategory: "Graphic Designs",
    rating: 4.4,
    image: require("../../assets/onboarding3.jpg"),
  },
];

export default serviceProviders;
